[wip] Implementing the UploadSnapshotsController
pulibrary/pdc_describe pull request #1028
Opened 2023-03-07 22:02 UTC by jrgriffiniii

2023-03-24 20:57 UTC, jrgriffiniii commented
The `browser-tools` Orb is failing with the following error:

```bash
GECKODRIVER_VERSION_NUM="$(echo "$GECKODRIVER_VERSION" | sed -E 's/v//')"

if geckodriver --version | grep "$GECKODRIVER_VERSION_NUM" >/dev/null 2>&1; then
  echo "$(geckodriver --version) has been installed to $(command -v geckodriver)"
else
  echo "Something went wrong; the specified version of Geckodriver could not be installed"
  exit 1
fi

Selected version of Geckodriver is: v0.32.2
Geckodriver is not currently installed; installing it
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html
```

2023-03-27 15:27 UTC, carolyncole requested changes
I feel like there will be more than one file on a work, but it seems like the controller method is dealing with a singular file.

I may have missed the point, os let me know if I did...

2023-03-28 13:28 UTC, jrgriffiniii commented on app/controllers/upload_snapshots_controller.rb
> +    @upload_snapshot = upload.create_snapshot
I am very sorry, I should have included a UI View for this (I am starting this right at the moment). Essentially, `Works` have multiple `uploads` (S3 files), which then have multiple `UploadSnapshots`. There is a one-to-many relationship between an `upload` and `UploadSnapshots`, however, I use the `uri` attribute to resolve to a unique `UploadSnapshot`.

I can be certain that the UI View clarifies this.

2023-04-05 18:14 UTC, carolyncole commented on db/migrate/20230303165757_create_upload_snapshots.rb
> +      t.bigint :version
Carolyn's imagination....
For each work you would have many entires:
{ files:[
   {filename:  'name1', checksum: 'abc1232'},
   {filename:  'name2', checksum: 'abc1232'},
   {filename:  'name3', checksum: 'abc1232'},
]
}

2023-04-12 14:24 UTC, jrgriffiniii commented
This is deprecated in favor of an improved implementation which I shall issue as a new pull request.

2023-04-12 14:24 UTC, closed without merging