Updated interface in Work Edit page to allow users to add and delete files
pulibrary/pdc_describe pull request #1042
Opened 2023-03-31 20:23 UTC by hectorcorrea

There are three major changes on this PR:
* Updated the work edit page to use DataTables so that files are paginated
* Updated the UX to allow the user to *add* files to an existing work
* Added the ability to *delete* an existing file from a work

2023-03-31 20:49 UTC, hectorcorrea commented on spec/system/work_spec.rb
> -    end
I have no idea what this test was attempting to test...but we do not allow the user to re-order the display of files so I removed it.

2023-04-03 12:37 UTC, carolyncole requested changes
@hectorcorrea I deployed this to staging and got errors when trying to delete files.
![Screenshot 2023-04-03 at 8 36 36 AM](https://user-images.githubusercontent.com/1599081/229511410-7a12fb10-8149-47c9-9897-9e646205fe7a.png)

2023-04-03 19:25 UTC, hectorcorrea commented
@carolyncole thank you so much tip, the spaces where indeed the problem. 

I've updated the code to use a safe value for the id of the HTML elements (based on the full path of the name) that prevents issue with any non-alphanumeric characters in the name.

2023-04-04 11:57 UTC, carolyncole approved these changes
@hectorcorrea now works for me.  Thanks for updating it!

2023-04-04 11:57 UTC, merged