Added ADR for additional checksums
pulibrary/pdc_describe pull request #1212
Opened 2023-05-24 13:39 UTC by kelynch

Closes #513

2023-05-24 17:02 UTC, carolyncole requested changes
I'm not sure if we should be recommending turning on checksums on upload, but the information you have here seems good.  Should it include the fact that none of our objects will have a SHA256, so calling the head_object will not create or retrieve one?

2023-05-24 17:02 UTC, carolyncole commented on architecture-decisions/0009-Additional-checksums.md
> +```bash
see the awscli response below matches the ruby client.
```
colec in ~/projects/pdc_describe (i1153-approve-require-doi) > aws s3api head-object --bucket $BUCKET --key $OBJECT_KEY --output json --checksum-mode ENABLED
{
    "AcceptRanges": "bytes",
    "LastModified": "2023-05-24T15:27:34+00:00",
    "ContentLength": 943363,
    "ETag": "\"9a9166e3ba6890cd43fe2ca5b77af496\"",
    "VersionId": "gxl2EbqsuApVtKlYv1cEkmQZtuEDk7.b",
    "ContentType": "image/png",
    "ServerSideEncryption": "AES256",
    "Metadata": {}
}
```

2023-05-24 20:49 UTC, kelynch commented on architecture-decisions/0009-Additional-checksums.md
> +pry(main)> object.checksum_sha256
Interesting, thanks for this.  Confusingly, I still got "nil" back on an object where I had enabled the checksum at upload and could get at that value through the API directly, and in the S3 web interface ("kate_test.txt" in the staging post-curation bucket).  I'm wondering what I may have missed.

2023-05-25 01:16 UTC, carolyncole commented on architecture-decisions/0009-Additional-checksums.md
> +pry(main)> object.checksum_sha256
Interesting, I just did a quick check was able to get them back with `object = s3_client.head_object({bucket: "pdc-describe-prod-precuration", key: "README.txt", checksum_mode: "ENABLED"})` It then had a sha256 checksum.

2023-05-30 18:09 UTC, carolyncole approved these changes

2023-05-30 18:38 UTC, merged