[wip] Ensuring that errors encountered for state transitions are handled with redirect responses for Works
pulibrary/pdc_describe pull request #1548
Opened 2023-10-02 20:04 UTC by jrgriffiniii

Resolves #527

2023-10-04 13:37 UTC, jrgriffiniii commented
There is one remaining failing test, and I am struggling to understand how this failure was introduced, and why this is exactly failing with the form submission:

https://app.circleci.com/pipelines/github/pulibrary/pdc_describe/4468/workflows/2cbd3e36-5697-4202-bf44-250292ebfe30/jobs/16478

![image](https://github.com/pulibrary/pdc_describe/assets/1443986/648db5f0-a93b-4fd3-95d7-fcc53848b66e)

2023-10-05 15:43 UTC, jrgriffiniii commented
This seems to be related to the form submission executed by Capybara/Selenium, specifically at the following line:

https://github.com/pulibrary/pdc_describe/pull/1548/files#diff-c37a48a9d764aaae554d5b61caa1176aa19ba56425fc7a4fa9d2aaaa524f68a1R120
I am troubleshooting this and finding that the selected `<option>` elements do not seem to be properly selected:

```bash
find("tr:last-child select[name='related_objects[][related_identifier_type]'] option[selected]")['innerHTML']
=> ""
```

2023-10-05 16:35 UTC, jrgriffiniii commented
Inspecting the `PATCH` parameters for this test yields the following:

```bash
[4] pry(#<WorksController>)> unescaped
=> "_method=patch&work[work_id]=&doi_read_only=10.34770/doc-1&title_main=Sowing the Seeds for More Usable Web Archives: A Usability Study of Archive-It&description=Download the README.txt for a detailed description of this dataset's content.&rights_identifiers[]=GPLv3&rights_identifiers[]=CC BY&creators[][given_name]=Samantha&creators[][family_name]=Abrams&creators[][orcid]=&creators[][affiliation]=&creators[][ror]=&creators[][given_name]=Alexis&creators[][family_name]=Antracoli&creators[][orcid]=&creators[][affiliation]=&creators[][ror]=&creators[][given_name]=Rachel&creators[][family_name]=Appel&creators[][orcid]=&creators[][affiliation]=&creators[][ror]=&creators[][given_name]=Celia&creators[][family_name]=Caust-Ellenbogen&creators[][orcid]=&creators[][affiliation]=&creators[][ror]=&creators[][given_name]=Sarah&creators[][family_name]=Dennison&creators[][orcid]=&creators[][affiliation]=&creators[][ror]=&creators[][given_name]=Sumitra&creators[][family_name]=Duncan&creators[][orcid]=&creators[][affiliation]=&creators[][ror]=&creators[][given_name]=Stefanie&creators[][family_name]=Ramsay&creators[][orcid]=&creators[][affiliation]=&creators[][ror]=&creators[][given_name]=Dionna&creators[][family_name]=Orn&creators[][orcid]=&creators[][affiliation]=&creators[][ror]=&keywords=&funders[][funder_name]=&funders[][award_number]=&funders[][award_uri]=&funders[][ror]=&related_objects[][related_identifier]=https://related.example.com&related_objects[][related_identifier_type]=&related_objects[][relation_type]=&contributors[][orcid]=&contributors[][given_name]=&contributors[][family_name]=&contributors[][role]=&organizational_contributors[][ror]=&organizational_contributors[][value]=&organizational_contributors[][type]=DATA_COLLECTOR&publisher=Princeton University&publication_year=2023&doi=10.34770/doc-1&ark=&resource_type=Dataset&resource_type_general=Dataset&version_number=1&group_id=1&embargo-date=&collection_tags=&commit=Save Work&existing_title_count=1&new_title_count=0&creator_count=8&contributor_count=0&related_object_count=0&work[deleted_files_count]=0&doi_read_only=10.34770/doc-1&wizard=true&user_orcid=&user_given_name=Dionna&user_family_name=Orn"
```

Capybara/Selenium does not seem to be submitting the HTML form values for `related_objects[][related_identifier_type]` and `related_objects[][relation_type]`:

```bash
related_objects[][related_identifier]=https://related.example.com&related_objects[][related_identifier_type]=&related_objects[][relation_type]=&
```

2023-10-05 19:13 UTC, jrgriffiniii commented
I apologize for the continued delays on this PR. I have made significant progress with https://github.com/pulibrary/pdc_describe/pull/1548/commits/9c8f6e41664b286e6c4ba4c3dfc2ee9f329be198, as there was a bug in which end-users were able to submit invalid "Additional Metadata" to Works which are within the `draft` state, which could then be persisted (but which should not be).

2023-10-09 16:06 UTC, jrgriffiniii commented
I have this stabilized finally, I can look to clean this PR and prepare this for review. Thank you again for your patience.

2023-10-10 15:44 UTC, carolyncole requested changes
@jrgriffiniii I am surprised that this PR is changing the validation criteria.  That said with your changes to the tests and the changes to the code it is hard to see if the code still works correctly.  I believe that the pending tests might be the ones that prove that work.valid_to_draft is being ignored at line 128.  I'm happy to be wrong, but I would like to see those pending test implemented to prove your change has not negative consequences.

2023-10-10 15:44 UTC, carolyncole commented on app/models/work.rb
> +      # There are cases where, before the README is attached, invalid metadata may be provided
I think this new set of code will ignore errors in valid_to_draft.  Could these checks be added there instead?

2023-10-10 15:44 UTC, carolyncole commented on spec/system/work_create_spec.rb
> +      xit "it renders a warning in response to form submissions" do
This should not be pending, as you are removing tests that previously existed

2023-10-10 15:44 UTC, carolyncole commented on spec/system/work_create_spec.rb
> +      xit "it renders a warning in response to form submissions" do
This should not be pending, as you are removing tests that previously existed

2023-10-10 15:44 UTC, carolyncole commented on spec/system/work_create_spec.rb
> +      page.save_screenshot
I'm guessing this is cruft
```suggestion
```

2023-10-10 15:44 UTC, carolyncole commented on spec/system/work_create_spec.rb
> +        xit "attempting to upload another README renders an error" do
Is there a reason for adding a pending test?  We rarely change the pending tests in the future.

2023-10-17 12:39 UTC, carolyncole approved these changes

2023-10-17 12:39 UTC, merged