Added Uppy to wizard step
pulibrary/pdc_describe pull request #1746
Opened 2024-04-09 16:10 UTC by hectorcorrea

Adds Uppy for file uploads during the Wizard (https://github.com/pulibrary/pdc_describe/pull/1719 added it to the Edit screen). Moved the JavaScript to an ES6 module and the code is now shared between the Edit and the Wizard.

The new functionality in the Wizard allows the user to clearly see the files that they are adding (see below) rather than just a message that says "4 files have been added". 

![Screenshot 2024-04-09 at 5 35 14 PM](https://github.com/pulibrary/pdc_describe/assets/568286/89d29ab3-3c6a-490b-9469-7730a90efaa4)

It does not use Uppy to upload the README step in the Wizard, see https://github.com/pulibrary/pdc_describe/issues/1731 for that feature.

Closes #1732

2024-04-10 19:02 UTC, hectorcorrea commented on app/javascript/entrypoints/pdc/work_edit_file_upload.es6
> +      restrictions: { maxNumberOfFiles: 20 }
We let Uppy handle the validation of the maximum numbers to upload.

2024-04-10 19:03 UTC, hectorcorrea commented on spec/system/work_upload_max_spec.rb
> -# frozen_string_literal: true
Removed this test because we now let Uppy handle the validation for the maximum number of files to upload instead of rolling our own.

2024-04-10 20:11 UTC, hectorcorrea commented on app/views/works/_form.html.erb
> -
This is now in app/javascript/entrypoints/pdc/work_edit_file_upload.es6

2024-04-10 20:11 UTC, hectorcorrea commented on app/javascript/entrypoints/pdc/work_edit_file_upload.es6
> +      restrictions: { maxNumberOfFiles: 20 },
We let Uppy handle the maximum number of files allowed to be uploaded

2024-04-10 20:12 UTC, hectorcorrea commented on app/javascript/entrypoints/pdc/pdc_ui_loader.es6
> -import MaximumFileUpload from './maximum_file_upload.es6';
Removed because Uppy handles this by itself, i.e. no need to write custom code

2024-04-10 21:14 UTC, hectorcorrea commented
There are still 3 failing tests but these tests depend on outside functionality (ORCID and ROR) and are not related to the changes introduced in this PR. 

Two of those failing tests  (the ones on `/spec/system/work_edit_spec.rb.rb`) even have a comment that says 

```
# This test depends on an outside API functioning reliably.
```

2024-04-11 11:27 UTC, carolyncole requested changes
~~This does seem to break the ORCID integration for Additional contributors.  If you paste `0000-0001-5443-596` into additional contributors on the additional metadata tab the user does not get filled in.  Interestingly the integration works for creators.~~. Nothing interesting about me coping the ORCID wrong... Will continue reviewing

2024-04-11 11:47 UTC, carolyncole commented on config/locales/en.yml
> +        actions: 'Once you have uploaded your files, click "next" to continue.'
Thanks!

2024-04-11 11:50 UTC, carolyncole reviewed
I'm looking at the tests.  I'm wondering if the Add files should be before the file list.  When going through the wizard on an existing work I got this page and was confused where the wizard went...
<img width="1515" alt="Screenshot 2024-04-11 at 7 49 34 AM" src="https://github.com/pulibrary/pdc_describe/assets/1599081/341714e4-c45c-4043-ac02-6594bdbab58f">

2024-04-11 11:55 UTC, carolyncole reviewed
clicking on delete does not seem to work...

And I am seeing a strange entry in the provenance log when I add files via the wizard
<img width="664" alt="Screenshot 2024-04-11 at 7 53 51 AM" src="https://github.com/pulibrary/pdc_describe/assets/1599081/34cecb48-7153-4edf-9aeb-702138e3d84f">

2024-04-11 13:54 UTC, carolyncole approved these changes
Hector noted that only files chosen at the same time show up in the provenance as a set.  If you choose one file from a folder and another file from another folder they will show up as two notes.

Additionally the unknown files was because we are sharing the DOI and some files already exisited

2024-04-11 13:54 UTC, merged