[wip] Ensures that one and only one README file is uploaded and that there is one or more files uploaded for any given Work
pulibrary/pdc_describe pull request #1813
Opened 2024-05-14 14:23 UTC by jrgriffiniii

Resolves #1772

2024-05-14 14:24 UTC, jrgriffiniii commented
I suspect that the error messages do not directly match what is required, I am very sorry. Once I have these matching, I can open this and request review.

2024-05-22 14:57 UTC, carolyncole requested changes
@jrgriffiniii this PR looks good, but I believe the user can add additional readme formats in the files.  That means the check in the validation should be removed.  As long as there is one the work is valid.  If there are 3 the work should still be valid.

2024-05-22 14:57 UTC, carolyncole commented on app/controllers/works_wizard_controller.rb
> +  def rescue_aasm_error
@jrgriffiniii why was this redefined here?

2024-05-22 14:57 UTC, carolyncole commented on app/services/work_validator.rb
> +      errors.add(:base, "You must provide only one README file upload") if work.readme_uploads.length > 1
I believe we will allow the user to add other version of the PDF in files

2024-05-28 18:23 UTC, carolyncole approved these changes

2024-05-28 18:30 UTC, carolyncole commented
@jrgriffiniii I'm happy to merge this PR.  I want to be certain you are aware that I can continue and submit even if I do not submit any other file than a readme.

2024-06-05 12:15 UTC, merged