Restructuring the S3QueryService Class to query AWS Bucket resources using ActiveStorage
pulibrary/pdc_describe pull request #301
Opened 2022-08-16 20:24 UTC by jrgriffiniii

Resolves #288

2022-08-17 20:08 UTC, carolyncole requested changes
@jrgriffiniii I really like the separation of pre-curation and post-curation files.  I added a couple comments and a question.

2022-08-17 20:08 UTC, carolyncole commented on app/models/work.rb
> +    if pre_curation_uploads.length > 20
Do we need to check the total of post and pre curated so we do not allow them to add more than 20 and then can not transfer them when they get approved?

2022-08-17 20:08 UTC, carolyncole commented on app/models/work.rb
> +    new_attachments.each do |attachment|
Could this block be extracted to a method, so that it can be utilized for both post and pre curated attachments?

2022-08-17 20:08 UTC, carolyncole commented on app/services/s3_query_service.rb
> +    return objects if model.nil?
I thought this code was to get the files that were put into S3, but are not represented yet in the database. Now it looks like this is not the case.  Is that a next step, or do I have the wrong idea about what this code does?

2022-08-22 17:04 UTC, carolyncole approved these changes

2022-08-22 17:18 UTC, carolyncole requested changes
@jrgriffiniii The code look great!
I'm unsure what is going on, but when I deploy the branch to staging this branch causes an error.  Sorry!  I would love to get this in.  It is possible the configurations need to change?

2022-08-22 17:19 UTC, hectorcorrea commented on app/services/s3_query_service.rb
> +  def model_s3_files
@jrgriffiniii -- If I understand this correctly `model_s3_files` includes files the user added via PDC Describe upload feature and that PDC Described pushed to S3, whereas `client_s3_files` includes files all files in the S3 folder (regardless of how they got there, e.g. uploaded via PDC Describe or manually uploaded to S3). 

`s3_files` returns the combination of these two methods and handles duplicates gracefully. Is that understanding correct? If so, could we add a comment to these methods to clarify this?

2022-08-22 19:07 UTC, carolyncole commented
@jrgriffiniii  I believe changing https://github.com/pulibrary/pdc_describe/blob/main/config/environments/staging.rb#L44 to `:amazon_pre_curation` and production also would solve the deployment issue.  It works on my local system

2022-08-23 20:14 UTC, carolyncole approved these changes

2022-08-23 21:03 UTC, hectorcorrea approved these changes

2022-08-23 21:03 UTC, merged