Publishing the ADR for the discussions and decisions made regarding the storage services used for files attached to Works
pulibrary/pdc_describe pull request #402
Opened 2022-09-09 19:43 UTC by jrgriffiniii

Resolves #379

2022-09-12 12:30 UTC, bess requested changes
Thank you for writing this! I'd like to talk about this as a team, though, because I'm not sure I understand all of it. 

In particular, I'm having trouble understanding this sentence and I wonder if we can re-word it to make it more clear:
"Advancing `Works` to the `post-curation` state will require that the S3 Bucket for `post-curation` S3 Objects be created in response to an update in the state of the `Work` object."

2022-09-12 20:20 UTC, jrgriffiniii commented on architecture-decisions/0005-work-attachment-curation-state.md
> +* Advancing `Works` to the `post-curation` state will require that the S3 Bucket for `post-curation` S3 Objects be created in response to an update in the state of the `Work` object.
A significant consequence of having `post-curation` S3 Objects managed without ActiveStorage is that ordering will *not* be preserved.

2022-09-22 18:42 UTC, jrgriffiniii commented
This might be blocked until https://github.com/pulibrary/pdc_describe/issues/405 is resolved. I will defer to others.

2022-09-26 14:50 UTC, bess approved these changes

2022-09-26 14:51 UTC, carolyncole submitted a review, later dismissed

2022-09-26 15:00 UTC, merged