Renders collection names as links
pulibrary/pdc_describe pull request #449
Opened 2022-09-28 16:45 UTC by hectorcorrea

![collection_name_as_link](https://user-images.githubusercontent.com/568286/192840796-93d43967-cc64-4e27-94db-91a955b93686.png)

Closes #334

2022-09-28 19:40 UTC, carolyncole requested changes
I'm thinking utilizing relative path would make this feature simpler in the long run.

2022-09-28 19:40 UTC, carolyncole commented on app/views/users/show.html.erb
> +      link_to(collection.title, collection_url(collection))
@hectorcorrea is there a reason not to utilize relative paths?
```suggestion
      link_to(collection.title, collection_path(collection))
```

2022-09-28 19:40 UTC, carolyncole commented on spec/spec_helper.rb
> +def capybara_root_url
I believe if we utilize relative urls this would not be needed

2022-09-28 19:40 UTC, carolyncole commented on spec/system/user_show_spec.rb
> +      pppl_url = capybara_root_url + collection_path(Collection.plasma_laboratory)
```suggestion
      pppl_url = collection_path(Collection.plasma_laboratory)
```

2022-09-29 12:50 UTC, hectorcorrea commented
@carolyncole good idea, I switched to use relative paths.

2022-09-29 13:31 UTC, carolyncole approved these changes

2022-09-29 13:31 UTC, merged