Migration test for attention test data
pulibrary/pdc_describe pull request #478
Opened 2022-10-11 18:01 UTC by Twade968

Fixes for ticket #469

2022-10-11 18:04 UTC, Twade968 commented
redescribed this record: https://dataspace.princeton.edu/handle/88435/dsp01xp68kk27p

```
<?xml version="1.0"?>
<resource xsi:schemaLocation='http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4/metadata.xsd' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns='http://datacite.org/schema/kernel-4'>
  <identifier identifierType='DOI'>10.34770/9425-b553</identifier>
  <creators>
    <creator>
      <creatorName>Wilterson, Andrew</creatorName>
      <givenName>Andrew</givenName>
      <familyName>Wilterson</familyName>
    </creator>
    <creator>
      <creatorName>Nastase, Samuel</creatorName>
      <givenName>Samuel</givenName>
      <familyName>Nastase</familyName>
    </creator>
    <creator>
      <creatorName>Bio, Branden</creatorName>
      <givenName>Branden</givenName>
      <familyName>Bio</familyName>
    </creator>
    <creator>
      <creatorName>Guterstam, Arvid</creatorName>
      <givenName>Arvid</givenName>
      <familyName>Guterstam</familyName>
    </creator>
    <creator>
      <creatorName>Graziano, Michael</creatorName>
      <givenName>Michael</givenName>
      <familyName>Graziano</familyName>
    </creator>
  </creators>
  <titles>
    <title>Attention and awareness in the dorsal attention network</title>
  </titles>
  <publisher>Princeton University</publisher>
  <resourceType resourceTypeGeneral='Dataset'/>
  <publicationYear>2020</publicationYear>
  <relatedIdentifiers>
    <relatedIdentifier relationType='IsIdenticalTo' relatedIdentifierType='ARK'>ark:/88435/dsp01xp68kk27p</relatedIdentifier>
  </relatedIdentifiers>
  <version>1</version>
  <rightsList>
    <rights rightsURI='https://creativecommons.org/licenses/by/4.0/' rightsIdentifier='CC BY'>Creative Commons Attribution 4.0 International</rights>
  </rightsList>
</resource>
```

2022-10-12 19:00 UTC, jrgriffiniii approved these changes

2022-10-13 17:20 UTC, bess requested changes
Please remove the puts statement at the end of this test.

2022-10-13 17:54 UTC, bess approved these changes

2022-10-13 17:55 UTC, merged

2022-10-13 17:57 UTC, matthewjchandler commented
This one is missing the Abstract. Here is the full XML that is currently in DataCite for this record (descriptions at the bottom):

```
<?xml version="1.0" encoding="UTF-8"?>
<resource
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4/metadata.xsd">
    <identifier identifierType="DOI">10.34770/9425-B553</identifier>
    <creators>
        <creator>
            <creatorName nameType="Personal">Wilterson, Andrew</creatorName>
            <givenName>Andrew</givenName>
            <familyName>Wilterson</familyName>
            <nameIdentifier nameIdentifierScheme="ORCID" schemeURI="https://orcid.org">https://orcid.org/0000-0002-4080-5386</nameIdentifier>
        </creator>
        <creator>
            <creatorName nameType="Personal">Nastase, Samuel</creatorName>
            <givenName>Samuel</givenName>
            <familyName>Nastase</familyName>
            <nameIdentifier nameIdentifierScheme="ORCID" schemeURI="https://orcid.org">https://orcid.org/0000-0001-7013-5275</nameIdentifier>
        </creator>
        <creator>
            <creatorName nameType="Personal">Bio, Branden</creatorName>
            <givenName>Branden</givenName>
            <familyName>Bio</familyName>
        </creator>
        <creator>
            <creatorName nameType="Personal">Guterstam, Arvid</creatorName>
            <givenName>Arvid</givenName>
            <familyName>Guterstam</familyName>
            <nameIdentifier nameIdentifierScheme="ORCID" schemeURI="https://orcid.org">https://orcid.org/0000-0002-3694-1318</nameIdentifier>
        </creator>
        <creator>
            <creatorName nameType="Personal">Graziano, Michael</creatorName>
            <givenName>Michael</givenName>
            <familyName>Graziano</familyName>
            <nameIdentifier nameIdentifierScheme="ORCID" schemeURI="https://orcid.org">https://orcid.org/0000-0002-7727-3475</nameIdentifier>
        </creator>
    </creators>
    <titles>
        <title>Attention and awareness in the dorsal attention network</title>
    </titles>
    <publisher>Princeton University</publisher>
    <publicationYear>2020</publicationYear>
    <resourceType resourceTypeGeneral="Dataset">Dataset</resourceType>
    <language>en</language>
    <sizes/>
    <formats/>
    <version/>
    <descriptions>
        <description xml:lang="en" descriptionType="Abstract">The attention schema theory (AST) posits a specific relationship between subjective awareness and attention, in which awareness is the control model that the brain uses to aid in the endogenous control of attention. We proposed that the right temporoparietal junction (TPJ) is involved in that interaction between awareness and attention. In previous experiments, we developed a behavioral paradigm in human subjects to manipulate awareness and attention. The paradigm involved a visual cue that could be used to guide a shift of attention to a target stimulus. In task 1, subjects were aware of the visual cue, and their endogenous control mechanism was able to use the cue to help control attention. In task 2, subjects were unaware of the visual cue, and their endogenous control mechanism was no longer able to use it to control attention, even though the cue still had a measurable effect on other aspects of behavior. Here we tested the two tasks while scanning brain activity in human volunteers. We predicted that the right TPJ would be active in relation to the cue in task 1, but not in task 2. This prediction was confirmed. The right TPJ was active in relation to the cue in task 1; it was not measurably active in task 2; the difference was significant. In our interpretation, the right TPJ is involved in a complex interaction in which awareness aids in the control of attention.</description>
    </descriptions>
</resource>
```