Fixes error saving resource_type_general
pulibrary/pdc_describe pull request #573
Opened 2022-10-27 21:10 UTC by hectorcorrea

The core of this PR is a little change to handle the fact that were using two different kind of values for resource_type_general. Sometimes we were using a symbol (e.g. `:DATASET`) and other times we were using a string (e.g. `"DATASET"`). That fix was easy at it is here:

In troubleshooting this I noticed that we do not allow the user to enter this value (and others) unless the have the right privileges, which is great, except that we were losing the **existing values** when a user edited a work. I changed the code to always show the values as HTML INPUT elements but make them readonly so that the user cannot change them but they are rendered and posted back on save.

![Screen Shot 2022-10-27 at 5 06 08 PM](https://user-images.githubusercontent.com/568286/198398080-751411fc-bcd8-4abe-a1c9-e082367c8d5e.png)

2022-10-27 21:12 UTC, hectorcorrea commented on app/services/form_to_resource_service.rb
> +        resource.resource_type_general = params["resource_type_general"].to_sym if params["resource_type_general"]
The call to `to_sym` here is what was missing to make sure we always use a symbol and not a string.

2022-10-28 13:22 UTC, mccalluc requested changes
I think there are some redundant bits that could be be left out... but if I'm missing the bigger picture, never mind.

2022-10-28 13:22 UTC, mccalluc commented on app/services/form_to_resource_service.rb
>      #  @param [User] current_user user currently authorized with the system.  Utilizes the current_user to validate access.
```suggestion
    #  @param [User] _current_user user currently authorized with the system.  Utilizes the _current_user to validate access.
```

2022-10-28 13:22 UTC, mccalluc commented on app/services/form_to_resource_service.rb
>      #  @param [User] current_user user currently authorized with the system.  Utilizes the current_user to validate access.
... but it's not actually used, so why not drop it entirely?

2022-10-28 13:22 UTC, mccalluc commented on app/services/form_to_resource_service.rb
> +        resource.resource_type_general = params["resource_type_general"].to_sym if params["resource_type_general"]
```suggestion
        resource.resource_type_general = params["resource_type_general"]&.to_sym
```
Should be equivalent?

2022-10-28 13:22 UTC, mccalluc commented on app/views/works/_curator_controlled_display.html.erb
> +    <input class="text-not-editable" type="text" id="doi" name="doi" value="<%= @work.resource.doi %>" readonly />
```suggestion
    <input id="doi" name="doi" value="<%= @work.resource.doi %>" readonly />
```

This class is being consistently applied with `readonly`, so I think just `readonly` would suffice? There's one CSS rule to update, but I think that's it. (See earlier comment.)

`text` is the default, so we could leave it off, I think?

(Same comment for all the inputs below.)

2022-10-28 13:22 UTC, mccalluc commented on app/assets/stylesheets/application.scss
> +  border-style: solid;
```suggestion
  border-style: solid;
  background: #f4f4f4;
```

and get rid of the redundant `text-not-editable`

2022-10-28 15:38 UTC, hectorcorrea commented
@mccalluc thanks for the suggestions. I've applied them.

2022-10-28 16:03 UTC, mccalluc approved these changes

2022-10-28 16:03 UTC, merged