Fixes for ticket #490
pulibrary/pdc_describe pull request #587
Opened 2022-11-01 18:07 UTC by Twade968

redescribed From this data set: https://dataspace.princeton.edu/handle/88435/dsp01bz60d033c

```
<?xml version="1.0"?>
<resource xsi:schemaLocation='http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4/metadata.xsd' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns='http://datacite.org/schema/kernel-4'>
  <identifier identifierType='DOI'>10.34770/xajd-5n64</identifier>
  <creators>
    <creator>
      <creatorName>Baldwin, Jane W</creatorName>
      <givenName>Jane W</givenName>
      <familyName>Baldwin</familyName>
    </creator>
    <creator>
      <creatorName>Dessy, Jay Benjamin</creatorName>
      <givenName>Jay Benjamin</givenName>
      <familyName>Dessy</familyName>
    </creator>
    <creator>
      <creatorName>Vecchi, Gabriel A</creatorName>
      <givenName>Gabriel A</givenName>
      <familyName>Vecchi</familyName>
    </creator>
    <creator>
      <creatorName>Oppenheimer, Michael</creatorName>
      <givenName>Michael</givenName>
      <familyName>Oppenheimer</familyName>
    </creator>
    <creator>
      <creatorName>Jia, Liwei</creatorName>
      <givenName>Liwei</givenName>
      <familyName>Jia</familyName>
    </creator>
    <creator>
      <creatorName>Gudgel, Richard G</creatorName>
      <givenName>Richard G</givenName>
      <familyName>Gudgel</familyName>
    </creator>
    <creator>
      <creatorName>Paffendorf, Karen</creatorName>
      <givenName>Karen</givenName>
      <familyName>Paffendorf</familyName>
    </creator>
  </creators>
  <titles>
    <title>
      Supporting data for Baldwin et al 2019 Temporally Compound Heat Waves and
      Global Warming: An Emerging Hazard
    </title>
  </titles>
  <publisher>GFDL Data Portal</publisher>
  <resourceType resourceTypeGeneral='Dataset'/>
  <publicationYear>2019</publicationYear>
  <relatedIdentifiers>
    <relatedIdentifier relationType='IsIdenticalTo' relatedIdentifierType='ARK'>ark:/88435/dsp01bz60d033c</relatedIdentifier>
  </relatedIdentifiers>
  <version>1</version>
  <rightsList>
    <rights rightsURI='https://creativecommons.org/licenses/by/4.0/' rightsIdentifier='CC BY'>Creative Commons Attribution 4.0 International</rights>
  </rightsList>
</resource>
```

2022-11-01 19:51 UTC, mccalluc reviewed
I feel out of my depth here: What I expected to see was that a given old XML representation could be migrated to a new JSON representation, and that the new form matches what we expect... But we're really just checking that the data can be entered into the form, and that the title matches.

I'd look to someone else for approval: I'm learning that I don't understand what migration means in this context.

2022-11-02 12:24 UTC, bess commented
@mccalluc You are correct that the purpose of this PR is not to test software functionality exactly. It is instead to validate that our re-description process is correct (i.e., "Has Tyler received enough training in DataCite from the RDOS team that he can re-describe these records the way they would?") and also to validate that our metadata mapping process is correct (i.e., "Given the form we've created, do we produce a complete and correct DataCite record, as judged by our subject matter experts in RDOS?") 

The epic is here: https://github.com/pulibrary/pdc_describe/issues/229

Once the data migration process is complete we probably won't keep all of these migration specs.

2022-11-02 12:25 UTC, bess approved these changes

2022-11-02 12:29 UTC, bess requested changes
@Twade968 I'm concerned that I don't see a description in this DataCite XML. I see you adding it in the spec, and I know we added it to the DataCite serialization, so I don't understand why we're not seeing it. Would you please run this again so we can double-check whether the description is truly missing from datacite? If it is, that's a bug we need to fix.

2022-11-14 17:23 UTC, bess approved these changes

2022-11-14 17:29 UTC, merged