Ensuring that multiple titles can be updated for an approved Work
pulibrary/pdc_describe pull request #866
Opened 2023-01-17 20:13 UTC by jrgriffiniii

2023-01-17 20:21 UTC, jrgriffiniii commented on spec/requests/works_spec.rb
> +          context "when authenticated as the submitter of the Work" do
This seems to be the failing case. I can ensure that this is fully resolved.

2023-01-18 15:36 UTC, jrgriffiniii commented
I was failing to reproduce these errors locally, I am going to proceed with resolving the outstanding failing test.

2023-01-18 20:44 UTC, carolyncole requested changes
@jrgriffiniii I am unsure if by fixing this "bug" we are introducing a bug.  We should check to see if we still want to limit when a depositor can edit the metadata before this gets merged.

I have no technical issue with this PR and I am not really requesting any changes,  I just want to block it from being merged until we can discuss it with RDOS.

2023-01-18 20:44 UTC, carolyncole commented on app/controllers/works_controller.rb
> -    elsif @work.approved? && @work.submitted_by?(current_user)
The requirement that a user can not edit an item they deposited was ticketed here: https://github.com/pulibrary/pdc_describe/issues/255.  Does removing this code introduce a bug?

2023-01-20 15:19 UTC, jrgriffiniii commented
Given the discussion held on 01/20/23, it was confirmed by the Product Owners that submitters should *not* be able to modify metadata.

2023-01-20 15:19 UTC, closed without merging